[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"
watchPatterns = ["production/**", "Dockerfile.railway"]

[build.args]
FRAPPE_BRANCH = "version-16"

[deploy]
healthcheckPath = "/api/method/ping"
healthcheckTimeout = 600
startCommand = ""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1
