[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway.pullonly"

[deploy]
healthcheckPath = "/api/method/ping"
healthcheckTimeout = 600
startCommand = ""
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
numReplicas = 1
