version: "3.7"
services:
  mariadb:
    image: docker.io/mariadb:11.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MARIADB_AUTO_UPGRADE: 1
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: docker.io/redis:alpine
    command: redis-server --tcp-keepalive 60 --timeout 0

  redis-queue:
    image: docker.io/redis:alpine
    command: redis-server --tcp-keepalive 60 --timeout 0

  frappe:
    image: docker.io/frappe/bench:latest
    command: sleep infinity
    environment:
      - SHELL=/bin/bash
    volumes:
      - ..:/workspace/development:cached
    working_dir: /workspace/development
    ports:
      - 8010-8015:8000-8005
      - 9010-9015:9000-9005

volumes:
  mariadb-data:
